# Generated by Django 6.0.2 on 2026-02-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Novela')),
                ('descripcion', models.TextField(verbose_name='Sinopsis')),
                ('imagen', models.ImageField(upload_to='portadas/', verbose_name='Portada')),
                ('link_drive', models.URLField(verbose_name='Enlace a Google Drive')),
            ],
        ),
    ]
