# Generated by Django 6.0.2 on 2026-02-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novela',
            name='genero',
            field=models.CharField(default='Fantasía', max_length=100, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='novela',
            name='tipo',
            field=models.CharField(choices=[('Novela Ligera', 'Novela Ligera (Japón)'), ('Web Novel', 'Web Novel (Corea)'), ('Novela China', 'Novela China (Wuxia/Xianxia)'), ('Otro', 'Otro')], default='Novela Ligera', max_length=50, verbose_name='Tipo de Novela'),
        ),
    ]
