# Generated by Django 6.0.2 on 2026-02-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_novela_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novela',
            name='tipo',
            field=models.CharField(choices=[('Novela Ligera', 'Novela Ligera (Japón)'), ('Novela Web', 'Novela Web (Corea)'), ('Novela China', 'Novela China (Wuxia/Xianxia)'), ('Otro', 'Otro')], default='Novela Ligera', max_length=50, verbose_name='Tipo de Novela'),
        ),
    ]
