# Generated by Django 6.0.2 on 2026-02-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_novela_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='novela',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]
